version: '3'

services:
    webserver:
        restart: unless-stopped
        build: ./webserver/
        ports:
            - 5050:9999
        environment:
            - DEBUG=1
        volumes:
            - ./webserver:/execute
        depends_on:
            - mongo
            - engine
    engine:
        restart: unless-stopped
        build: ./engine/
        environment:
            - DEBUG=1
        volumes:
            - ./engine:/execute
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: unless-stopped
        command: /usr/bin/mongod --bind_ip_all --replSet rs0 --journal --dbpath /data/db
        volumes:
            - ./mongodbdata:/data/db
        ports: 
            - 127.0.0.1:27017:27017