version: '3'

services:
    webserver:
        restart: unless-stopped
        build: ./webserver/
        ports:
            - 5050:9999
    attacker:
        restart: unless-stopped
        build: ./attacker/
    flag-sub:
        restart: unless-stopped
        build: ./flag_sub/
    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - ./mongodbdata:/data/db
        ports: #Only for test
            - 127.0.0.1:27017:27017