version: '3'

services:
    webserver:
        restart: unless-stopped
        build: ./webserver/
        ports:
            - 5050:9999
        environment:
            - DEBUG=0
        depends_on:
            - mongo
            - engine
    engine:
        restart: unless-stopped
        build: ./engine/
        environment:
            - DEBUG=0
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - ./mongodbdata:/data/db
