version: '3'

services:
    webserver:
        restart: unless-stopped
        build: ./webserver/
        ports:
            - 5050:9999
        environment:
            - DEBUG=1
        volumes:
            - ./webserver:/execute
        depends_on:
            - mongo
    attacker:
        restart: unless-stopped
        build: ./attacker/
        environment:
            - DEBUG=1
        volumes:
            - ./attacker:/execute
        depends_on:
            - mongo
    flag-sub:
        restart: unless-stopped
        build: ./flag_sub/
        environment:
            - DEBUG=1
        volumes:
            - ./flag_sub:/execute
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - ./mongodbdata:/data/db
        ports: 
            - 127.0.0.1:27017:27017